AllCops:
  RunRailsCops: true
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'plugins/**/*'
    - 'db/schema.rb'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'

Metrics/LineLength:
  Enabled: false